name:                Game-Dangerous
version:             0.9.0.0
github:              "Mushy-pea/Game-Dangerous"
license:             Custom
author:              "Steven Tinsley"
maintainer:          "steven.tinsley81@gmail.com"
copyright:           "None"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Games

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Mushy-pea/Game-Dangerous#readme>

dependencies:
- base >= 4.7 && < 5
- matrix >= 0.3
- split >= 0.2
- StateVar >= 1.2
- OpenAL >= 1.7
- ObjectName >= 1.1
- bytestring >= 0.10
- OpenGL >= 3.0
- array >= 0.5
- OpenGLRaw >= 3.3
- containers >= 0.6
- binary >= 0.8
- GLURaw >= 2.0
- clock >= 0.8
- GLUT >= 2.7
- random >= 1.2
- cryptohash-sha256 >= 0.11

library:
  source-dirs: src

executables:
  Game-Dangerous-exe:
    main:                Main.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -O
    dependencies:
    - Game-Dangerous

  ImportModel:
    main:                ImportModel.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -O
    dependencies:
    - Game-Dangerous

  Server:
    main:                Server.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -O
    dependencies:
    - Game-Dangerous

tests:
  Game-Dangerous-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Game-Dangerous

