module ExtraGPLC_Debug where

gplcSymbol :: [Char] -> Int -> [Char]
gplcSymbol "AI_Conversation1:f5b196ec492f1c62c746e7c9e55d3415d8ec464e120efd0ab98e3542437ba087" d_list_index
  | d_list_index == 0 = "w: "
  | d_list_index == 1 = "u: "
  | d_list_index == 2 = "v: "
  | d_list_index == 3 = "targetU1: "
  | d_list_index == 4 = "targetV1: "
  | d_list_index == 5 = "msgLength0: "
  | d_list_index == 6 = "nodeLength0: "
  | d_list_index == 7 = "nodeLength1: "
  | d_list_index == 8 = "nodeLength2: "
  | d_list_index == 9 = "nodeLength3: "
  | d_list_index == 10 = "nodeLength4: "
  | d_list_index == 11 = "nodeLength5: "
  | d_list_index == 12 = "nodeLength6: "
  | d_list_index == 13 = "one: "
  | d_list_index == 14 = "two: "
  | d_list_index == 15 = "three: "
  | d_list_index == 16 = "four: "
  | d_list_index == 17 = "five: "
  | d_list_index == 18 = "six: "
  | d_list_index == 19 = "seven: "
  | d_list_index == 20 = "eight: "
  | d_list_index == 21 = "nine: "
  | d_list_index == 22 = "num10: "
  | d_list_index == 23 = "num11: "
  | d_list_index == 24 = "num12: "
  | d_list_index == 25 = "targetU: "
  | d_list_index == 26 = "targetV: "
  | d_list_index == 27 = "branchTable0*: "
  | d_list_index == 28 = "branchTable0_0: "
  | d_list_index == 29 = "branchTable0_1: "
  | d_list_index == 30 = "branchTable0_2: "
  | d_list_index == 31 = "branchTable1*: "
  | d_list_index == 32 = "branchTable1_3: "
  | d_list_index == 33 = "branchTable1_4: "
  | d_list_index == 34 = "branchTable2*: "
  | d_list_index == 35 = "branchTable2_5: "
  | d_list_index == 36 = "branchTable2_6: "
  | d_list_index == 37 = "branchTable3*: "
  | d_list_index == 38 = "branchTable3_7: "
  | d_list_index == 39 = "branchTable3_8: "
  | d_list_index == 40 = "branchTable*1: "
  | d_list_index == 41 = "branchTable*2: "
  | d_list_index == 42 = "branchTable*3: "
  | d_list_index == 43 = "add: "
  | d_list_index == 44 = "set: "
  | d_list_index == 45 = "on: "
  | d_list_index == 46 = "off: "
  | d_list_index == 47 = "switch: "
gplcSymbol "DoorController:0d4432cdb28b886f1be960f65b93c387386b63ff6201a4eb6a968e2e9d644e7e" d_list_index
  | d_list_index == 0 = "w: "
  | d_list_index == 1 = "u: "
  | d_list_index == 2 = "v: "
  | d_list_index == 3 = "w1: "
  | d_list_index == 4 = "zero: "
  | d_list_index == 5 = "two: "
  | d_list_index == 6 = "three: "
  | d_list_index == 7 = "four: "
  | d_list_index == 8 = "leftSpeed: "
  | d_list_index == 9 = "rightSpeed: "
  | d_list_index == 10 = "maxLeft: "
  | d_list_index == 11 = "minLeft: "
  | d_list_index == 12 = "add: "
  | d_list_index == 13 = "set: "
  | d_list_index == 14 = "velocity: "
  | d_list_index == 15 = "left: "
gplcSymbol program_name d_list_index = show d_list_index ++ ": "

recoverGplcSymbols :: [Int] -> [Char] -> Int -> [Char]
recoverGplcSymbols [] prog_name i = []
recoverGplcSymbols (x:xs) prog_name i = gplcSymbol prog_name i ++ show x ++ " " ++ recoverGplcSymbols xs prog_name (i + 1)

