module ExtraGPLC_Debug where

gplcSymbol :: [Char] -> Int -> [Char]
gplcSymbol "AI_Conversation1:ce69e987ecb94736a3cfbed19326479bbef750f7908f47fae6a2b3e1e10978be" d_list_index
  | d_list_index == 0 = "w: "
  | d_list_index == 1 = "u: "
  | d_list_index == 2 = "v: "
  | d_list_index == 3 = "msgLength0: "
  | d_list_index == 4 = "nodeLength0: "
  | d_list_index == 5 = "nodeLength1: "
  | d_list_index == 6 = "nodeLength2: "
  | d_list_index == 7 = "nodeLength3: "
  | d_list_index == 8 = "nodeLength4: "
  | d_list_index == 9 = "nodeLength5: "
  | d_list_index == 10 = "nodeLength6: "
  | d_list_index == 11 = "one: "
  | d_list_index == 12 = "two: "
  | d_list_index == 13 = "three: "
  | d_list_index == 14 = "four: "
  | d_list_index == 15 = "five: "
  | d_list_index == 16 = "six: "
  | d_list_index == 17 = "seven: "
  | d_list_index == 18 = "eight: "
  | d_list_index == 19 = "nine: "
  | d_list_index == 20 = "num10: "
  | d_list_index == 21 = "num11: "
  | d_list_index == 22 = "num12: "
  | d_list_index == 23 = "targetU: "
  | d_list_index == 24 = "targetV: "
  | d_list_index == 25 = "branchTable0*: "
  | d_list_index == 26 = "branchTable0_0: "
  | d_list_index == 27 = "branchTable0_1: "
  | d_list_index == 28 = "branchTable0_2: "
  | d_list_index == 29 = "branchTable1*: "
  | d_list_index == 30 = "branchTable1_3: "
  | d_list_index == 31 = "branchTable1_4: "
  | d_list_index == 32 = "branchTable2*: "
  | d_list_index == 33 = "branchTable2_5: "
  | d_list_index == 34 = "branchTable2_6: "
  | d_list_index == 35 = "branchTable3*: "
  | d_list_index == 36 = "branchTable3_7: "
  | d_list_index == 37 = "branchTable3_8: "
  | d_list_index == 38 = "branchTable*1: "
  | d_list_index == 39 = "branchTable*2: "
  | d_list_index == 40 = "branchTable*3: "
  | d_list_index == 41 = "add: "
  | d_list_index == 42 = "set: "
  | d_list_index == 43 = "on: "
  | d_list_index == 44 = "off: "
  | d_list_index == 45 = "switch: "
gplcSymbol program_name d_list_index = show d_list_index ++ ": "

recoverGplcSymbols :: [Int] -> [Char] -> Int -> [Char]
recoverGplcSymbols [] prog_name i = []
recoverGplcSymbols (x:xs) prog_name i = gplcSymbol prog_name i ++ show x ++ " " ++ recoverGplcSymbols xs prog_name (i + 1)

